worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;

    # ========= Gzip =========
    gzip on;
    gzip_min_length 1k;
    gzip_comp_level 6;
    gzip_types
      text/plain
      text/css
      application/javascript
      application/json
      image/svg+xml;
    gzip_vary on;

    server {
        listen 80;
        server_name localhost;

        # ========= 前端 dist =========
        root /your/dist;
        index index.html;

        # SPA 路由兼容（必须）
        location / {
            try_files $uri $uri/ /index.html;
        }

        # ========= API 反向代理 =========
        location /api/ {
            proxy_pass http://127.0.0.1:8000/api/;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            # 上传大小限制
            client_max_body_size 50M;
        }

        # ========= 照片目录 =========
        location ^~ /Media/ {
            alias /home/hcy/mySite/Media/;

            # 缓存优化（摄影站推荐）
            expires 1d;
            add_header Cache-Control "public";
        }

        # ========= 博客目录 =========
        location ^~ /Blogs/ {
            alias /home/hcy/mySite/Blogs/;

            # 缓存优化（摄影站推荐）
            expires 1d;
            add_header Cache-Control "public";
        }


        # ========= 静态资源缓存 =========
        location ~* \.(js|css|png|jpg|jpeg|webp|gif|svg|ico|woff|woff2)$ {
            expires 1d;
            add_header Cache-Control "public, immutable";
        }

        access_log off;
    }
}
