worker_processes  auto;

events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;

    gzip on;
    gzip_min_length 1k;
    gzip_comp_level 6;
    gzip_types
      text/plain
      text/css
      application/javascript
      application/json
      image/svg+xml;
    gzip_vary on;

    server {
        listen 8080;            # 不用 80，避免和系统 nginx 冲突
        server_name localhost;

        root /home/hcy/mySite/dist;   # ⚠️ 改成你的 dist 绝对路径
        index index.html;

        location / {
            try_files $uri /index.html;
        }

	location ~* \.(js|css|png|jpg|jpeg|webp|gif|svg|ico|woff|woff2)$ {
            expires 1y;
            add_header Cache-Control "public, immutable";
        }

        access_log off;
    }
}

